---
# tasks file for pyenv https://github.com/pyenv/pyenv#basic-github-checkout
- name: RegistIsPyenv
  shell: bash -lc "which pyenv"
  ignore_errors: True
  register: is_pyenv
  tags: pyenv

- name: Install Pyenv
  block:
    - name: Git clone pyenv
      ansible.builtin.git:
        repo: 'https://github.com/pyenv/pyenv.git'
        dest: '{{ ansible_user_dir }}/.pyenv'

    - name: Copy .bash_profile
      ansible.builtin.copy:
        src: .bash_profile
        dest: '{{ ansible_user_dir }}/.bash_profile.d/pyenv'
  tags: pyenv
  when: is_pyenv.rc == 1
