---
# tasks file for docker https://docs.docker.com/engine/install/ubuntu/
- name: RegistIsDocker
  shell: bash -lc "which docker"
  ignore_errors: True
  register: is_docker
  tags: docker

- name: Install Docker
  block:
    - name: Remove packages
      apt:
        name: '{{ item }}'
        state: absent
      with_items:
        - docker
        - docker-engine
        - docker.io
        - containerd
        - runc

    - name: Install packages
      apt:
        name: '{{ item }}'
        update_cache: yes
        state: present
      with_items:
        - ca-certificates
        - curl
        - gnupg
        - lsb-release

    - name: Add an Apt signing key, uses whichever key is at the URL
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        keyring: /usr/share/keyrings/docker-archive-keyring.gpg
        state: present

    - name: Template docker.list
      ansible.builtin.template:
        src: etc/apt/sources.list.d/docker.list
        dest: /etc/apt/sources.list.d/docker.list

    - name: Install Docker packages
      apt:
        name: '{{ item }}'
        update_cache: yes
        state: present
      with_items:
        - docker-ce
        - docker-ce-cli
        - containerd.io

    - name: Add ansible_user to docker group
      ansible.builtin.user:
        name: '{{ ansible_user }}'
        groups: docker
        append: yes

    - name: Make sure a service unit is running
      ansible.builtin.systemd:
        state: started
        name: docker
        enabled: yes

  tags: docker
  when: is_docker.rc == 1
  become: True
